languageCode = "pt-BR"
languageName = "Português Brasil"
languageDirection = "ltr"
weight = 1

#title = "Educação"
copyright = "&copy; 2024 Todos os direitos reservados"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["fisica", "matematica"]
  description = "Um tema leve e poderoso para Hugo contruído usando o Tailwind CSS."

[params.author]
  name = "Professor Wagner"
  image = "img/wagner.jpg"
  headline = "Educação é o futuro! :book:"
  bio = "Formado em Licenciatura em Física, Pós graduado em Gestão de Projetos e Analista Profissional na área de TI :dog:"
  links = [
    # { x-twitter = "https://twitter.com/" },
    # { facebook = "https://facebook.com/" },
    # { linkedin = "https://linkedin.com/" },
    # { youtube = "https://youtube.com/" },
  ]